name: Node.js CI/CD Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || echo "No tests"

    - name: Build project
      run: npm run build || echo "No build script"

    - name: Deploy (simulation)
      run: echo "Deploy step here (e.g., Docker push or SSH deploy)"
