name: Node.js CI/CD with Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test || echo "No tests found"

    # 构建 Docker 镜像
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest .

    # 登录 Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 推送镜像
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
